CREATE DATABASE IF NOT EXISTS DB_NAME;
CREATE ROLE IF NOT EXISTS 'wp_role';
GRANT ALL PRIVILEGES ON DB_NAME.* to 'wp_role';
CREATE USER IF NOT EXISTS DB_USER
	IDENTIFIED BY 'DB_PASSWORD';
GRANT 'wp_role' TO DB_USER;
DROP USER 'mysql'@'localhost';
ALTER USER 'root'@'localhost' IDENTIFIED BY 'DB_ROOT_PASSWORD';
FLUSH PRIVILEGES;
